# Generated by Django 5.1.3 on 2024-11-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_otp_expires_at_otp_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp_code',
            new_name='otp',
        ),
    ]
