# Generated by Django 5.1.3 on 2024-11-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_alter_otp_expires_at_alter_otp_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
