# Generated by Django 5.1.3 on 2024-11-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_remove_product_available_stock_remove_product_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='offer',
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
