# Generated by Django 5.1.3 on 2024-11-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_remove_product_offer_product_product_delete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_delete',
            new_name='delete_opt',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='delete_opt',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
