# Generated by Django 5.1.3 on 2024-11-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_remove_variant_offer_product_offer_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
