# Generated by Django 5.1.3 on 2024-12-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_alter_variant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.CharField(choices=[('3ml', '3ml'), ('6ml', '6ml'), ('12ml', '12ml'), ('10ml', '10ml'), ('20ml', '20ml'), ('100ml', '100ml'), ('20gm', '20gm'), ('50gm', '50gm'), ('100gm', '100gm')], max_length=255),
        ),
    ]
