# Generated by Django 5.1.3 on 2024-12-07 07:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallet_User',
            new_name='Wallet',
        ),
        migrations.RenameModel(
            old_name='Wallet_transactions',
            new_name='WalletTransactions',
        ),
    ]
