# Generated by Django 5.1.3 on 2024-12-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0003_alter_wallet_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='wallettransactions',
            old_name='date_of_transaction',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='wallettransactions',
            old_name='transaction_for',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='wallettransactions',
            old_name='wallet_id',
            new_name='wallet',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='date',
        ),
        migrations.RemoveField(
            model_name='wallettransactions',
            name='amount_received',
        ),
        migrations.RemoveField(
            model_name='wallettransactions',
            name='amount_sent',
        ),
        migrations.RemoveField(
            model_name='wallettransactions',
            name='delete',
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=6, null=True),
        ),
    ]
