# Generated by Django 5.1.3 on 2024-12-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0005_spinhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
