# Generated by Django 5.1.3 on 2024-12-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0006_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinhistory',
            name='is_won',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='spinhistory',
            name='reward_amount',
            field=models.FloatField(),
        ),
    ]
