# Generated by Django 5.1.3 on 2024-12-17 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0009_wallettransactions_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinhistory',
            name='is_won',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spinhistory',
            name='spin_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
