# Generated by Django 5.1.3 on 2024-12-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0010_alter_spinhistory_is_won_alter_spinhistory_spin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinhistory',
            name='is_won',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='spinhistory',
            name='spin_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
