# Generated by Django 5.1.3 on 2024-11-29 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0006_orders_alter_orderitem_order_delete_order'),
        ('product_app', '0008_remove_product_status'),
        ('user_profile_app', '0004_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_added',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('serial_number', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_online_id', models.CharField(blank=True, default='0000', max_length=50, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('coupon_name', models.CharField(blank=True, max_length=50, null=True)),
                ('coupon_discount', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile_app.userprofile')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('size', models.CharField(default='toadd', max_length=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('final_product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('Order Pending', 'Order Pending'), ('Order confirmed', 'Order confirmed'), ('Shipped', 'Shipped'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Order Pending')),
                ('cancel_return_confirm', models.BooleanField(default=False)),
                ('accept_order', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_all', to='order_app.order')),
                ('product_added', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_app.variant')),
            ],
        ),
        migrations.AlterField(
            model_name='cancelled_order',
            name='ordered_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_app.orderitems'),
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
