# Generated by Django 5.1.3 on 2024-12-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0007_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='payment_st',
            field=models.BooleanField(default=False),
        ),
    ]
