# Generated by Django 5.1.3 on 2024-12-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0008_orderitems_payment_st'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='payment_st',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10),
        ),
    ]
