# Generated by Django 5.1.3 on 2024-12-07 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0009_remove_orderitems_payment_st_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='CancelledOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('request_date', models.DateField(auto_now_add=True, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('ordered_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_app.orderitems')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cancelled_order',
        ),
    ]
