# Generated by Django 5.1.3 on 2024-12-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0018_alter_order_status_alter_orderitems_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='status',
            field=models.CharField(choices=[('Pending', 'Order Pending'), ('Processing', 'Processing'), ('Confirmed', 'Order confirmed'), ('Shipped', 'Shipped'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Requested', 'Requested')], default='Pending', max_length=255),
        ),
    ]
