# Generated by Django 5.1.4 on 2024-12-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0023_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
