# Generated by Django 5.1.3 on 2024-11-12 08:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('category_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_listed', models.BooleanField(default=True)),
                ('category_unit', models.CharField(blank=True, choices=[('ml', 'Milligram'), ('bottle', 'Bottle')], max_length=50, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
