# Generated by Django 5.1.3 on 2024-11-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0002_alter_category_category_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
