# Generated by Django 5.1.3 on 2024-11-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
