# Generated by Django 5.1.3 on 2024-12-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0005_alter_category_category_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_unit',
            field=models.CharField(blank=True, choices=[('ml', 'Milligram'), ('bottle', 'Bottle'), ('gm', 'Gram')], max_length=50, null=True),
        ),
    ]
