# Generated by Django 5.1.3 on 2024-12-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0006_alter_category_category_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_unit',
            field=models.CharField(blank=True, choices=[('ml', 'Milligram'), ('bottle', 'Bottle'), ('box', 'Box')], max_length=50, null=True),
        ),
    ]
