# Generated by Django 5.1.3 on 2024-12-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0007_alter_cart_coupon'),
        ('coupon_app', '0002_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupons',
        ),
    ]
