# Generated by Django 5.1.3 on 2024-12-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_app', '0003_delete_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_purchase_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
