# Generated by Django 5.1.3 on 2024-11-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_amount_without_coupon',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
