# Generated by Django 5.1.3 on 2024-11-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0003_cart_coupon_cart_coupon_active_checkout_coupon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
