# Generated by Django 5.1.3 on 2024-11-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0005_rename_user_cart_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
