# Generated by Django 5.1.3 on 2024-12-09 14:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0007_alter_cart_coupon'),
        ('product_app', '0009_alter_variant_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='Whishlist',
        ),
    ]
