# Generated by Django 5.1.4 on 2024-12-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0008_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, null=True),
        ),
    ]
