# Generated by Django 5.1.3 on 2024-11-20 09:35

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_app', '0002_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Image must be a valid file type: .jpg, .jpeg, .png, or .webp', regex='^.*\\.(jpg|jpeg|png|webp)$')], verbose_name='image'),
        ),
    ]
